### ISSUE TITLE
Migrate to null-safety

### ISSUE THREAD

**Issue by steven-spiel** [policygenius/optimizely-plugin#10]
How long until we can expect the plugin to [migrate to null safety](https://dart.dev/null-safety/migration-guide#step2-migrate)? This is really important for my team. @longhorn499

**Comment by longhorn499** [comment]
> How long until we can expect the plugin to [migrate to null safety](https://dart.dev/null-safety/migration-guide#step2-migrate)? This is really important for my team. @longhorn499

Hi @steven-spiel, we don't currently have plans to do this, but if you submit a PR I will gladly review it and publish a new release 👍

**Comment by afermin** [comment]
HI @longhorn499. We're are very interested in migrating the project to null safety. I already have the update in a branch. Can I get permission to to push it and create the PR?

**Comment by longhorn499** [comment]
> HI @longhorn499. We're are very interested in migrating the project to null safety. I already have the update in a branch. Can I get permission to to push it and create the PR?

Go for it! 🚀 🚀

**Comment by longhorn499** [comment]
Resolved with #11 and released with `v0.1.3` 🙏
